"""empty message

Revision ID: 1d6c7e1246c2
Revises: d78e1c2b8de5
Create Date: 2025-03-15 11:15:37.795693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6c7e1246c2'
down_revision: Union[str, None] = 'd78e1c2b8de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'upper_cased_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('upper_cased_name', sa.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
