"""empty message

Revision ID: 3a484a01c68e
Revises: 1d6c7e1246c2
Create Date: 2025-03-16 13:33:07.001875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a484a01c68e'
down_revision: Union[str, None] = '1d6c7e1246c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_category')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('entry_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=6),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.drop_column('toilet')
        batch_op.drop_column('skibidi')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skibidi', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('toilet', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('entry_type',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    op.create_table('_alembic_tmp_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('lower_cased_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
