"""empty message

Revision ID: 4461c6a91105
Revises: 743a8dd16256
Create Date: 2025-03-22 18:02:11.288998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4461c6a91105'
down_revision: Union[str, None] = '743a8dd16256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.drop_constraint('fk_transaction_account_id_account', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transaction_account_id_account'), 'account', ['account_id'], ['id'])
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_transaction_account_id_account'), type_='foreignkey')
        batch_op.create_foreign_key('fk_transaction_account_id_account', 'account', ['account_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
