"""empty message

Revision ID: 57023219c7c0
Revises: 8bba98980a5f
Create Date: 2025-06-05 19:40:10.179397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57023219c7c0'
down_revision: Union[str, None] = '8bba98980a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_suggested_category_transaction_id_transaction', type_='foreignkey')
        batch_op.drop_constraint('fk_suggested_category_category_id_category', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_suggested_category_transaction_id_transaction'), 'transaction', ['transaction_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_suggested_category_category_id_category'), 'category', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_suggested_category_category_id_category'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_suggested_category_transaction_id_transaction'), type_='foreignkey')
        batch_op.create_foreign_key('fk_suggested_category_category_id_category', 'category', ['category_id'], ['id'])
        batch_op.create_foreign_key('fk_suggested_category_transaction_id_transaction', 'transaction', ['transaction_id'], ['id'])

    # ### end Alembic commands ###
