"""empty message

Revision ID: 6a7b4056f171
Revises: d0aa5f2da640
Create Date: 2025-06-02 16:24:42.169474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7b4056f171'
down_revision: Union[str, None] = 'd0aa5f2da640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_category', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
