"""empty message

Revision ID: 743a8dd16256
Revises: 4b6c93d04726
Create Date: 2025-03-16 21:30:46.168139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "743a8dd16256"
down_revision: Union[str, None] = "4b6c93d04726"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.Inspector.from_engine(conn)  # type: ignore

    # Check if the temporary table exists and drop it if it does
    if inspector.has_table("_alembic_tmp_transaction"):
        op.execute("DROP TABLE _alembic_tmp_transaction")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "account_id",
                sa.Integer(),
                nullable=False,
                server_default="1",
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_transaction_account_id_account"),
            "account",
            ["account_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_transaction_account_id_account"), type_="foreignkey"
        )
        batch_op.drop_column("account_id")

    # ### end Alembic commands ###
