"""empty message

Revision ID: d1b93a9e8c2e
Revises: 4461c6a91105
Create Date: 2025-04-06 23:47:21.611418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b93a9e8c2e'
down_revision: Union[str, None] = '4461c6a91105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('initial_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('initial_balance',
               existing_type=sa.Numeric(precision=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
